name: Update Index

on:
  push:
    paths:
      - 'meetups/**.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Update index.md
        run: |
          python .github/scripts/update_index.py
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update index.md with new meetups"
          git push